function AIInsights({ insights = [] }) {

  return (

    <div className="bg-slate-900 border border-slate-800 rounded-2xl shadow-xl p-6 text-white h-full">

      {/* Header */}

      <div className="flex justify-between items-center mb-6">

        <div>

          <h2 className="text-2xl font-bold">

            🧠 AI Financial Insights

          </h2>

          <p className="text-gray-400 text-sm mt-1">

            Personalized recommendations generated by AI

          </p>

        </div>

        <div className="bg-green-500/20 text-green-400 px-4 py-2 rounded-xl text-sm font-semibold">

          Live Analysis

        </div>

      </div>

      {/* AI Summary */}

      <div className="bg-slate-800 rounded-xl p-5 mb-5">

        <h3 className="text-lg font-semibold mb-3">

          Financial Health Summary

        </h3>

        <p className="text-gray-300 leading-7">

          Your financial profile looks stable. AI has analyzed your
          income, savings, expenses and spending habits to provide
          personalized recommendations below.

        </p>

      </div>

      {/* Insights */}

      <div className="space-y-3">

        {insights.length > 0 ? (

          insights.map((item, index) => (

            <div
              key={index}
              className="flex items-start gap-3 bg-slate-800 rounded-xl p-4 hover:bg-slate-700 transition"
            >

              <div className="text-green-400 text-lg">

                ✔

              </div>

              <p className="text-gray-200">

                {item}

              </p>

            </div>

          ))

        ) : (

          <div className="text-gray-400">

            AI insights are being generated...

          </div>

        )}

      </div>

      {/* Recommendation */}

      <div className="mt-6 bg-gradient-to-r from-blue-600/20 to-indigo-600/20 border border-blue-500/20 rounded-xl p-5">

        <h3 className="text-lg font-semibold mb-2">

          ⭐ AI Recommendation

        </h3>

        <p className="text-gray-300">

          Continue increasing your monthly savings and consider
          investing more into long-term SIPs to achieve your future
          financial goals faster.

        </p>

      </div>

    </div>

  );

}

export default AIInsights;